### ISSUE TITLE
rename to something other than fish

### ISSUE THREAD

**Issue by bacongobbler** [fishworks/fish#37]
the name and path (`/usr/local/bin/fish` on linux/macOS) conflicts with another tool of the same name: [Fish Shell](http://fishshell.com/).

**Comment by bacongobbler** [comment]
Here's a list of the suggested names thus far. Please vote by spamming the heck out of your emojis!

👍 for `fsh`
😄 for `phsh`
❤️ for `gofish`

**Comment by stevemoser** [comment]
FYI `fsh` is used by IBM's shell tool: https://github.com/ibm-functions/shell

**Comment by AlexWayfer** [comment]
> FYI fsh is used by IBM's shell tool: https://github.com/ibm-functions/shell

It reminded me of https://github.com/hanami/hanami/issues/445

Oh, this IBM!

**Comment by bacongobbler** [comment]
I'm personally in favour of `fsh` because it's short, sweet and easy to type on the keyboard, so there's my vote.

I'll note that I'll probably still choose the name I prefer overall, but I wanted to get a feel for how others felt about the name before going ahead and renaming the CLI and the [fish food](https://github.com/fishworks/fish-food/blob/master/Food/fish.lua).

@stevemoser thanks for pointing that out! Given that `fsh` appears to be catering to a very specific use case (IBM Cloud Functions) as opposed to fish shell, I'd still be okay with using `fsh` as a name. I'm pretty sure every TLA (three-letter acronym) is probably taken at this point.

**Comment by tonejito** [comment]
Yeah I thought of this after dinner and I think `phsh` sounds like "phishing shell", which is not what this tool is about.

I came up with an idea: `gfsh`

> Homebrew is to `brew` like GoFish is to `gfsh`

I also voted for plain `gofish` though :P

**Comment by bacongobbler** [comment]
haha if that was the name I'd always pronounce gfsh as giffish. `gofish` it is! I'll rename the CLI and fish food after work.

**Comment by bitwalker** [comment]
Please (pretty please) name this something other than Fish - name collisions happen, generally not a big deal, but these are both so closely related (one a shell, one a tool for the shell) that it seems needlessly harmful not only to this project, but Fish (the shell) as well. Looking for help on Google will be difficult, there will be confusion around tagging on StackOverflow, even conversations about "Fish" will be confusing until you know which one somebody is taking about. Fish isn't an obscure shell either, it's quite popular, so it seems a little unfair to lay claim to the name because it happens to be your own. I know other people with the last name Fish, there is at least one in the Elixir community, which one of you should own the rights to the name for their pet project? Hopefully you see my point, which isn't to say you _can't_ name this project Fish, but if you want it to be successful _and_ want to be a good OSS steward, I think it is worth going back to the drawing board on the name, you've drawn enough attention that crowd sourcing a name is probably going to be fairly easy.

I've made the same mistake before and ultimately found a better name for my project, so don't feel like Fish is the only good option! If you insist on using Fish in the name, then I think `gofish` is the only good option you've listed, but I beg you to reconsider.

**Comment by bacongobbler** [comment]
> Looking for help on Google will be difficult, there will be confusion around tagging on StackOverflow, even conversations about "Fish" will be confusing until you know which one somebody is taking about.

With the rename to `gofish`, users can tag issues as `gofish` on Stack Overflow, Google with "gofish ...", communicate on twitter using the #gofish hashtag, etc. This is the same issue with how developers search for issues related to Go by searching with "golang ..." and can continue to Google using "fish shell ..." for the latter.

Honestly I'm really disappointed that this issue is being **incredibly** overblown. Fish is going to be the project name, and `gofish` will be the name of the binary in /usr/local/bin. I'm not going to rename the project to something else. Sorry if that causes confusion.

**Comment by bacongobbler** [comment]
implemented in https://github.com/fishworks/fish/commit/2eb84940f4e48dc63d2e51109b7626b6694ddc1c. Updates to the fish food and site are rolling out.

**Comment by bacongobbler** [comment]
update: the project has been renamed across the board to GoFish.
